name: CI
on:
  schedule:
    - cron: "0 4,8,12,16,20 * * *"
    - cron: "0 0 * * *"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
      GIT: ${{secrets.GIT}}
      AI: ${{secrets.AI}}
      RUNNUM: ${{ github.run_number }}
      REPO: ${{ github.repository }}
    steps:
      - name: GIT clone the main repo !
        run: |
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          cd /home/runner/work/${{ github.event.repository.name }}
          git clone https://github.com/${{ github.repository }}.git
      - name: Run a multi-line script
        run: |
          sudo apt update -y
          sudo apt install ffmpeg -y
          BOTDIR="/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
          cd $BOTDIR
          git pull
          git checkout main
          git commit -am "sync sub"
          git push https://Wumbee01:${GIT}@github.com/${REPO}.git sub
          git checkout sub
          chmod +x $BOTDIR/main.sh
          timeout $(( 4 * 60 * 60 - 60 ))s bash -c "bash ${BOTDIR}/main.sh" || exit
          kill $!
